version: "3.8"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    networks:
      backend_network:
        ipv4_address: 172.18.0.13
    ports:
      - "8082:8082"
    command: sh -c "java -jar target/tracker-server.jar"

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
    external: true